CREATE DATABASE startup_finder;
CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT,fullname VARCHAR(100),email VARCHAR(100) UNIQUE,password VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
SHOW DATABASES;
USE startup_finder;
SHOW TABLES;
CREATE TABLE startups (id INT PRIMARY KEY AUTO_INCREMENT,title VARCHAR(255),description TEXT,domain VARCHAR(100),required_skills TEXT,created_by INT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE applications (id INT PRIMARY KEY AUTO_INCREMENT,startup_id INT,applicant_id INT,status VARCHAR(50) DEFAULT 'Pending');
CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT,fullname VARCHAR(100),email VARCHAR(100) UNIQUE,password VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
SELECT * FROM users;
CREATE TABLE profiles(id INT PRIMARY KEY AUTO_INCREMENT,user_id INT,college VARCHAR(255),course VARCHAR(255),bio TEXT,skills TEXT,github VARCHAR(255),linkedin VARCHAR(255));
CREATE TABLE cofounder_requests(id INT PRIMARY KEY AUTO_INCREMENT,sender_id INT,receiver_id INT,status VARCHAR(50) DEFAULT 'Pending');
USE startup_finder;
INSERT INTO startups (title, description, domain, required_skills, created_by) VALUES ('AI Interview Platform','Helps students prepare for interviews using AI','AI','Node.js, React, MongoDB',1);
select * from users;
describe users;
select * from users;
select * from users;
SELECT * FROM users ORDER BY id DESC;
SELECT DATABASE();
SELECT * FROM users;
DELETE FROM users;
ALTER TABLE users AUTO_INCREMENT = 1;
use startup_finder;
select * from users;
select * from startups;
DESC profiles;
DROP TABLE IF EXISTS profiles;
CREATE TABLE profiles(id INT PRIMARY KEY AUTO_INCREMENT,user_id INT UNIQUE,college VARCHAR(255),course VARCHAR(255),bio TEXT,skills TEXT,github VARCHAR(255),linkedin VARCHAR(255),FOREIGN KEY(user_id)REFERENCES users(id) ON DELETE CASCADE);
select * from profiles;
DROP TABLE IF EXISTS applications;
CREATE TABLE applications(id INT PRIMARY KEY AUTO_INCREMENT,startup_id INT,applicant_id INT,status VARCHAR(50) DEFAULT 'Pending',FOREIGN KEY(startup_id)REFERENCES startups(id)ON DELETE CASCADE,FOREIGN KEY(applicant_id)REFERENCES users(id)ON DELETE CASCADE);
select * from applications;
DROP TABLE IF EXISTS cofounder_requests;
CREATE TABLE cofounder_requests(id INT PRIMARY KEY AUTO_INCREMENT,sender_id INT,receiver_id INT,status VARCHAR(50) DEFAULT 'Pending',FOREIGN KEY(sender_id)REFERENCES users(id)ON DELETE CASCADE,FOREIGN KEY(receiver_id)REFERENCES users(id) ON DELETE CASCADE);
select * from cofounder_requests;
SELECT * FROM users;
SELECT * FROM profiles;
SELECT * FROM cofounder_requests;